version: '3.8'

services:
  geopandas-app:
    build: .
    working_dir: /usr/src/app/
    ports:
      - "8080:8080"
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=8080
    volumes:
      - .:/usr/src/app/
    command: flask run
